// Generated by gencpp from file racecarDepth/ObsPose.msg
// DO NOT EDIT!


#ifndef RACECARDEPTH_MESSAGE_OBSPOSE_H
#define RACECARDEPTH_MESSAGE_OBSPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace racecarDepth
{
template <class ContainerAllocator>
struct ObsPose_
{
  typedef ObsPose_<ContainerAllocator> Type;

  ObsPose_()
    : header()
    , x()
    , y()
    , dist()
    , angle()  {
    }
  ObsPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(_alloc)
    , y(_alloc)
    , dist(_alloc)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_type;
  _x_type x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_type;
  _y_type y;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _dist_type;
  _dist_type dist;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::racecarDepth::ObsPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::racecarDepth::ObsPose_<ContainerAllocator> const> ConstPtr;

}; // struct ObsPose_

typedef ::racecarDepth::ObsPose_<std::allocator<void> > ObsPose;

typedef boost::shared_ptr< ::racecarDepth::ObsPose > ObsPosePtr;
typedef boost::shared_ptr< ::racecarDepth::ObsPose const> ObsPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::racecarDepth::ObsPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::racecarDepth::ObsPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace racecarDepth

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'racecarDepth': ['/home/aaron/racecar_ws4.1/src/racecarDepth/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::racecarDepth::ObsPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::racecarDepth::ObsPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecarDepth::ObsPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecarDepth::ObsPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecarDepth::ObsPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecarDepth::ObsPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::racecarDepth::ObsPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e77b1edb72076900365c7711a9bdb5d";
  }

  static const char* value(const ::racecarDepth::ObsPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e77b1edb7207690ULL;
  static const uint64_t static_value2 = 0x0365c7711a9bdb5dULL;
};

template<class ContainerAllocator>
struct DataType< ::racecarDepth::ObsPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "racecarDepth/ObsPose";
  }

  static const char* value(const ::racecarDepth::ObsPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::racecarDepth::ObsPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32[] x\n\
float32[] y\n\
float32[] dist\n\
float32[] angle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::racecarDepth::ObsPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::racecarDepth::ObsPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.dist);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObsPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::racecarDepth::ObsPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::racecarDepth::ObsPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "dist[]" << std::endl;
    for (size_t i = 0; i < v.dist.size(); ++i)
    {
      s << indent << "  dist[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dist[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACECARDEPTH_MESSAGE_OBSPOSE_H
